
import { GoogleGenAI } from "@google/genai";
import { ImageData } from "../types";

export const generateBlendedImage = async (
  adultImage: ImageData,
  childImage: ImageData
): Promise<{ imageUrl: string; text?: string }> => {
  // Always create a new instance right before the API call to get the latest API key.
  // The API key must be obtained exclusively from the environment variable process.env.API_KEY.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

  const prompt = `Create a highly realistic and emotionally resonant photograph featuring the adult from the first image and the child from the second image. They should be depicted in a warm, natural embrace (hugging). Ensure consistent lighting across both subjects, matching textures, and perfect anatomical accuracy. The result should look like a professional-grade studio photograph with a soft, slightly blurred background to emphasize their emotional connection. Maintain the distinctive facial features and characteristics of both individuals.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          {
            inlineData: {
              data: adultImage.base64,
              mimeType: adultImage.mimeType,
            },
          },
          {
            inlineData: {
              data: childImage.base64,
              mimeType: childImage.mimeType,
            },
          },
          { text: prompt },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      },
    });

    let imageUrl = '';
    let text = '';

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the model.");
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      } else if (part.text) {
        text = part.text;
      }
    }

    if (!imageUrl) {
      throw new Error("The model did not return an image part.");
    }

    return { imageUrl, text };
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};
